- name: Install mysql server
  apt:
    name: mysql-server
    state: present 

- name: Install python mysqldb
  apt:
    name: python-mysqldb
    state: present
    
- name: Create db
  mysql_db:
    name: mms
    state: present
